### ISSUE TITLE
Dodo CT Log Server Refused My Request

### ISSUE THREAD

**Issue by CitizenBeta2** [sectigo/CTLogs-AcceptedRoots#45]
Hi, I'm David Miller. I'm the admin of pki.davidmiller.top. I noticed that my root certificate has been add to dodo's "not_trusted" root list. But when I use ct-submit trying to upload my server auth certiifcate, ct-submit shows that { "error_message": "untrusted self-signed certificate", "success": false }. I don't know where is it goes wrong. 

Compiled ct-submit: "https://repo.davidmiller.top/software/ct-submit"
Command I use: "./ct-submit dodo.ct.comodo.com <./test.crt >./test.sct"

**Comment by Raytonne** [comment]
I believe new root certs haven't been added to Dodo.
Also, I think @LeviMarvin and you uploaded DER encoded roots, but Rob fixed them before running the update scripts.

**Comment by CitizenBeta2** [comment]
> I believe new root certs haven't been added to Dodo. Also, I think @LeviMarvin and you uploaded DER encoded roots, but Rob fixed them before running the update scripts.

I misunderstood the guide and Rob (@robstradling) fixed it. I'm wondering when the dodo server will trust my root certificate. I've waited for 4-5 month. By the way, may I have a cross-sign root certifcate with your root?(https://raytonne.cn/PKI/)  Please leave me an email if it is ok.

**Comment by Raytonne** [comment]
> By the way, may I have a cross-sign root certifcate...

Please use the contact form on our website; someone will respond during working hours.

**Comment by CitizenBeta2** [comment]
> @CitizenBeta2 Although this is the source repository for our logs' lists of accepted roots, the process of deploying list updates is currently manual and under the control of our Ops team. I have sent Ops a deployment request, but I don't yet have an ETA.

I cannot access dodo server up to now. Thank you for your work.

**Comment by robstradling** [comment]
The latest update to Dodo's accepted roots has just been deployed.
